=== diegosoriarios/SemestreIV/DSE/07_restricoes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="movimentos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cadastros">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="filmes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="filme" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="codigo" type="cod" />
                                                    <xs:element name="titulo" type="xs:string" />
                                                    <xs:element name="categoria">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Ouro"></xs:enumeration>
                                                                <xs:enumeration value="Prata"></xs:enumeration>
                                                                <xs:enumeration value="Bronze"></xs:enumeration>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="tipo_filme">
                                                        <xs:simpleType>
                                                            <xs:restriction>
                                                                <xs:enumeration value="P"></xs:enumeration>
                                                                <xs:enumeration value="E"></xs:enumeration>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="exemplares">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="codigo_exemplar" type="cod" />
                                                                <xs:element name="tipo_exemplar">
                                                                    <xs:complexType>
                                                                        <xs:choice>
                                                                            <xs:element name="cd" type="xs:string" />
                                                                            <xs:element name="dvd" type="xs:string" />
                                                                        </xs:choice>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="alugado">
                                                                    <xs:simpleType>
                                                                        <xs:restriction>
                                                                            <xs:enumeration value="Sim"></xs:enumeration>
                                                                            <xs:enumeration value="Nao"></xs:enumeration>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                                <xs:element name="valor" type="val_decimal" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="emprestimos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="emprestimo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="codigo" type="cod" />
                                        <xs:element name="data" type="xs:string" />
                                        <xs:element name="cliente" type="xs:string" />
                                        <xs:element name="itens">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="item" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="exemplar" type="cod" />
                                                                <xs:element name="valor" type="val_decimal" />
                                                                <xs:element name="desconto">
                                                                    <xs:complexType>
                                                                        <xs:choice>
                                                                            <xs:element name="desconto_valor" type="val_decimal" />
                                                                            <xs:element name="porcentagem" type="val_decimal" />
                                                                        </xs:choice>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="data_devolucao" type="xs:string" minOccurs="0"/>
                                                                <xs:element name="data_prevista" type="xs:string" />
                                                                <xs:element name="multa" type="val_decimal" minOccurs="0"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--FACETS-->
        <xs:simpleType name="cod">
            <xs:restriction base="integer">
                <xs:totalDigits value="5"></xs:totalDigits>
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="val_decimal">
            <xs:restriction base="decimal">
                <xs:fractionDigits value="2"></xs:fractionDigits>
            </xs:restriction>
        </xs:simpleType>
    <!--END-->
</xs:schema>

=== diegosoriarios/SemestreIV/DSE/07_restricoes.xml
<?xml version="1.0" encoding="UTF-8"?>
<movimentos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="07_restricoes.xsd">
    <cadastros>
        <filmes>
            <filme>
                <codigo>1</codigo>
                <titulo>SILENCIO DOS INOCENTES</titulo>
                <categoria>Ouro</categoria>
                <tipo_filme>E</tipo_filme>
                <exemplares>
                    <codigo_exemplar>00005</codigo_exemplar>
                    <tipo_exemplar>
                        <dvd>567898</dvd>
                    </tipo_exemplar>
                    <alugado>Sim</alugado>
                    <valor>2.50</valor>
                </exemplares>				
            </filme>
            <filme>
                <codigo>00002</codigo>
                <titulo>A ERA DO GELO</titulo>
                <categoria>Prata</categoria>
                <tipo_filme>E</tipo_filme>
                <exemplares>
                    <codigo_exemplar>00005</codigo_exemplar>
                    <tipo_exemplar>
                        <cd>111111</cd>
                    </tipo_exemplar>
                    <alugado>NÃ£o</alugado>
                    <valor>2.50</valor>
                </exemplares>				
            </filme>			
        </filmes>
    </cadastros>	
    <emprestimos>
        <emprestimo>
            <codigo>00001</codigo>
            <data>2008-10-16</data>
            <cliente>PEDRO DA SILVA</cliente>
            <itens>
                <item>
                    <exemplar>00005</exemplar>
                    <valor>4.50</valor>
                    <desconto>
                        <desconto_valor>0.50</desconto_valor>
                    </desconto>
                    <data_devolucao>2008-10-16</data_devolucao>
                    <data_prevista>2008-10-15</data_prevista>
                    <multa>4.00</multa>
                </item>
                <item>
                    <exemplar>00005</exemplar>
                    <valor>4.50</valor>
                    <desconto>
                        <desconto_valor>0.50</desconto_valor>
                    </desconto>
                    <data_devolucao>2008-10-16</data_devolucao>
                    <data_prevista>2008-10-15</data_prevista>
                    <multa>4.00</multa>
                </item>
            </itens>
        </emprestimo>
        <emprestimo>
            <codigo>00002</codigo>
            <data>2008-10-12</data>
            <cliente>ERASMO CARLOS</cliente>
            <itens>
                <item>
                    <exemplar>00005</exemplar>
                    <valor>4.50</valor>
                    <desconto>
                        <porcentagem>0.50</porcentagem>
                    </desconto>
                    <data_prevista>2008-10-15</data_prevista>
                </item>
                <item>
                    <exemplar>00005</exemplar>
                    <valor>4.50</valor>
                    <desconto>
                        <desconto_valor>0.50</desconto_valor>
                    </desconto>
                    <data_devolucao>2008-10-16</data_devolucao>
                    <data_prevista>2008-10-15</data_prevista>
                    <multa>4.00</multa>
                </item>
            </itens>
        </emprestimo>
    </emprestimos>
</movimentos>
