=== diegosoriarios/SemestreIV/DSE/trabalho02.dtd
<!ELEMENT vendas (venda*)>
<!ELEMENT venda (data, total, pessoas)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT pessoas (cliente, vendedor)>
<!ELEMENT tipo_pessoa (#PCDATA)>
<!ELEMENT nascimento (#PCDATA)>
<!ELEMENT cliente (telefone, nascimento, conjuge?)>
<!ELEMENT vendedor (telefone, nascimento, conjuge?)>
<!ELEMENT conjuge (nome, endereco, telefone)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT endereco (#PCDATA)>
<!ELEMENT telefone (#PCDATA)>
<!ATTLIST venda numero CDATA #REQUIRED>

=== diegosoriarios/SemestreIV/DSE/trabalho01.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE vendas SYSTEM "trabalho02.dtd">
<vendas>
	<venda numero="1">
		<data>2016-03-07</data>
		<total>R$ 100,00</total>
        <pessoas>
            <cliente>
                <telefone>12345678</telefone>
                <nascimento>11/11/91</nascimento>
                <conjuge>
                    <nome>Maria</nome>
                    <endereco>Rua 1, 5</endereco>
                    <telefone>98765432</telefone>
                </conjuge>
            </cliente>
            <vendedor>
                <telefone>19734682</telefone>
                <nascimento>22/05/90</nascimento>
            </vendedor>
        </pessoas>
	</venda>
</vendas>
